import {
  NAutoComplete,
  NCascader,
  NCheckbox,
  NColorPicker,
  NDatePicker,
  NDynamicInput,
  NDynamicTags,
  NInput,
  NInputNumber,
  NInputOtp,
  NMention,
  NRadio,
  NRate,
  NSelect,
  NSlider,
  NSwitch,
  NTimePicker,
  NTransfer,
  NTreeSelect,
  NUpload,
} from 'naive-ui'

export const FORM_ITEM_COMPONENT_MAP = {
  'n-input': { component: NInput, modelValue: 'value', defaultValue: null },
  'n-auto-complete': { component: NAutoComplete, modelValue: 'value', defaultValue: null },
  'n-cascader': { component: NCascader, modelValue: 'value', defaultValue: null },
  'n-color-picker': { component: NColorPicker, modelValue: 'value', defaultValue: null },
  'n-checkbox': { component: NCheckbox, modelValue: 'checked', defaultValue: false },
  'n-date-picker': { component: NDatePicker, modelValue: 'value', defaultValue: null },
  'n-dynamic-input': { component: NDynamicInput, modelValue: 'value', defaultValue: [] },
  'n-dynamic-tags': { component: NDynamicTags, modelValue: 'value', defaultValue: [] },
  'n-input-number': { component: NInputNumber, modelValue: 'value', defaultValue: null },
  'n-input-otp': { component: NInputOtp, modelValue: 'value', defaultValue: null },
  'n-mention': { component: NMention, modelValue: 'value', defaultValue: null },
  'n-radio': { component: NRadio, modelValue: 'checked', defaultValue: null },
  'n-rate': { component: NRate, modelValue: 'value', defaultValue: null },
  'n-select': { component: NSelect, modelValue: 'value', defaultValue: null },
  'n-slider': { component: NSlider, modelValue: 'value', defaultValue: 0 },
  'n-switch': { component: NSwitch, modelValue: 'value', defaultValue: false },
  'n-time-picker': { component: NTimePicker, modelValue: 'value', defaultValue: null },
  'n-transfer': { component: NTransfer, modelValue: 'value', defaultValue: [] },
  'n-tree-select': { component: NTreeSelect, modelValue: 'value', defaultValue: null },
  'n-upload': { component: NUpload, modelValue: 'file-list', defaultValue: [] },
}

export type FromItemComponentType = keyof typeof FORM_ITEM_COMPONENT_MAP
