/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '//': RouteRecordInfo<'//', '/', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/settings-base/': RouteRecordInfo<'/settings-base/', '/settings-base', Record<never, never>, Record<never, never>>,
    '/settings-base/institution-management': RouteRecordInfo<'/settings-base/institution-management', '/settings-base/institution-management', Record<never, never>, Record<never, never>>,
    '/settings-base/institution-management/department-management': RouteRecordInfo<'/settings-base/institution-management/department-management', '/settings-base/institution-management/department-management', Record<never, never>, Record<never, never>>,
    '/settings-base/institution-management/institution-info': RouteRecordInfo<'/settings-base/institution-management/institution-info', '/settings-base/institution-management/institution-info', Record<never, never>, Record<never, never>>,
    '/settings-base/institution-management/payment-management': RouteRecordInfo<'/settings-base/institution-management/payment-management', '/settings-base/institution-management/payment-management', Record<never, never>, Record<never, never>>,
    '/settings-base/institution-management/role-management': RouteRecordInfo<'/settings-base/institution-management/role-management', '/settings-base/institution-management/role-management', Record<never, never>, Record<never, never>>,
    '/settings-base/institution-management/user-management': RouteRecordInfo<'/settings-base/institution-management/user-management', '/settings-base/institution-management/user-management', Record<never, never>, Record<never, never>>,
    '/settings-base/institution-management/ward-management': RouteRecordInfo<'/settings-base/institution-management/ward-management', '/settings-base/institution-management/ward-management', Record<never, never>, Record<never, never>>,
    '/test/': RouteRecordInfo<'/test/', '/test', Record<never, never>, Record<never, never>>,
    '/test/a/': RouteRecordInfo<'/test/a/', '/test/a', Record<never, never>, Record<never, never>>,
    '/test/b/': RouteRecordInfo<'/test/b/', '/test/b', Record<never, never>, Record<never, never>>,
    '/test/form-demo/': RouteRecordInfo<'/test/form-demo/', '/test/form-demo', Record<never, never>, Record<never, never>>,
  }
}
