/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '//': RouteRecordInfo<'//', '/', Record<never, never>, Record<never, never>>,
    '/test/': RouteRecordInfo<'/test/', '/test', Record<never, never>, Record<never, never>>,
    '/test/a/': RouteRecordInfo<'/test/a/', '/test/a', Record<never, never>, Record<never, never>>,
    '/test/b/': RouteRecordInfo<'/test/b/', '/test/b', Record<never, never>, Record<never, never>>,
    '/test/form-demo/': RouteRecordInfo<'/test/form-demo/', '/test/form-demo', Record<never, never>, Record<never, never>>,
  }
}
